# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb55cc63e8140664f2b96c6031b45a2ccda0992e876c14d72887a65f9833d4e95c9b0f0b6897b8a5edbdf6e6bc22deb78f98f40988d2fa953297e4d78293786d

test:
  secret_key_base: ecc6f1f319ef10981998ad69716795b176aeb3626a7ac674d4cb05fe2a9edb2f6e6ee6107725ac9855de845f10487e14e58383c5d5ffd12d1cf2c9cadc9b2793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
